version: "3.8"
services:
  jenkins:
    build: .
    container_name: jenkins-container
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      BIND_TOKEN: "password"
